/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static String linter(String location) {
        Path path = Paths.get(location);

        Scanner linterScanner;
        {
            try {
                linterScanner = new Scanner(path);
                int lineNumber = 1;
                StringBuilder results = new StringBuilder();

                while (linterScanner.hasNextLine()) {
                    String line = linterScanner.nextLine();
                    if (line.lastIndexOf(";") != line.length() - 1 &&
                            line.indexOf("{") != line.length() - 1 &&
                            line.indexOf("}") != 0 &&
                            !line.contains("if") && !line.contains("else"))
                    {
                        results.append("Line " + lineNumber + " is missing a semi-colon:\n" + line + "\n");
                    }
                    lineNumber++;
                }
                return results.toString();

            } catch (FileNotFoundException e) {
                e.printStackTrace();
                System.out.println("file not found");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return "error";
    }

    public static void main(String[] args) {
        System.out.println(linter("../linter/resources/gates.js"));
    }
}
