/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void checkRestaurantConstructorFunctionality() {
        Restaurant restaurant = new Restaurant("Pizza Hut", 2);
        assertEquals(restaurant.name, "Pizza Hut");
        assertEquals(restaurant.price, 2);
    }

    @Test public void checkRestaurantToString() {
        Restaurant restaurant = new Restaurant("Pizza Hut", 2);
        String restaurantString = restaurant.toString();
        assertTrue(restaurantString.contains("Name: Pizza Hut"));
    }

    @Test public void checkReviewConstructorFunctionality() {
        Review review = new Review("Absolute garbage, ew", "Gordon Ramsay", 0);
        assertEquals(review.body, "Absolute garbage, ew");
        assertEquals(review.rating, 0);
    }
}
